version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=DarthVader
      - POSTGRES_PASSWORD=0303456lalalalalalala
    ports:
      - '5432:5432'
